import { Inject, Injectable, Logger, NotFoundException, type OnApplicationBootstrap } from '@nestjs/common';

import type { CanvasNode } from '@email-builder/shared/types';
import { normalizeNode, templates as starters } from '@email-builder/shared/utils';

import { dslToTree, parseDsl } from '../ai/engine/dsl';
import { generateDsl } from '../ai/engine/generator';
import { decodeDataUrl, newId } from '../common/ids';
import { Prisma } from '../generated/prisma/client';
import { PrismaService } from '../prisma/prisma.service';

export type TemplateKind = 'starter' | 'user' | 'ai';

export interface TemplateSummary {
    id: string;
    name: string;
    kind: TemplateKind;
    prompt: string | null;
    hasDsl: boolean;
    screenshot: string | null;
    createdAt: string;
    updatedAt: string;
}

export interface TemplateDetail extends TemplateSummary {
    root: CanvasNode;
    dsl: string | null;
}

const SUMMARY_SELECT = {
    id: true,
    name: true,
    kind: true,
    prompt: true,
    dsl: true,
    screenshotType: true,
    createdAt: true,
    updatedAt: true,
} as const;

/** Large starters generated by the rules engine, so they carry DSL for Gemini examples. */
const LARGE_STARTERS: { name: string; prompt: string; type: string; tone: string }[] = [
    {
        name: 'Large product launch',
        prompt: 'Product launch announcement for Lumen Labs, a SaaS startup, introducing our new Insights dashboard.',
        type: 'announcement',
        tone: 'professional',
    },
    {
        name: 'Large monthly newsletter',
        prompt: 'Monthly newsletter for Bluebird Coffee, a friendly neighbourhood cafe.',
        type: 'newsletter',
        tone: 'friendly',
    },
    {
        name: 'Large seasonal sale',
        prompt: 'End of season sale for Northwind, an online clothing store. 30% off everything.',
        type: 'promo',
        tone: 'urgent',
    },
];

const STOP_WORDS = new Set([
    'email',
    'template',
    'with',
    'that',
    'this',
    'from',
    'your',
    'about',
    'make',
    'create',
    'write',
    'design',
    'tone',
    'friendly',
    'professional',
    'please',
    'campaign',
    'send',
    'like',
    'have',
    'them',
    'they',
    'their',
]);

@Injectable()
export class TemplatesService implements OnApplicationBootstrap {
    private readonly logger = new Logger(TemplatesService.name);

    constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}

    async onApplicationBootstrap(): Promise<void> {
        try {
            const added = await this.seed();
            if (added > 0) this.logger.log(`seeded ${added} starter templates`);
        } catch (error) {
            this.logger.error(`startup failed: ${(error as Error).message}`);
        }
    }

    /* ---------- reads ---------- */

    async list(query: { q?: string; kind?: TemplateKind; limit?: number }): Promise<TemplateSummary[]> {
        const limit = query.limit ?? 100;
        if (query.q) return this.searchText(query.q, query.kind, limit);
        const rows = await this.prisma.template.findMany({
            where: query.kind ? { kind: query.kind } : undefined,
            orderBy: { updatedAt: 'desc' },
            take: limit,
            select: SUMMARY_SELECT,
        });
        return rows.map((r) => this.summary(r));
    }

    async get(id: string): Promise<TemplateDetail> {
        const row = await this.prisma.template.findUnique({ where: { id }, select: { ...SUMMARY_SELECT, root: true } });
        if (!row) throw new NotFoundException('not found');
        return { ...this.summary(row), root: row.root as unknown as CanvasNode, dsl: row.dsl };
    }

    async screenshot(id: string): Promise<{ bytes: Buffer; type: string }> {
        const row = await this.prisma.template.findUnique({
            where: { id },
            select: { screenshot: true, screenshotType: true },
        });
        if (!row?.screenshot || !row.screenshotType) throw new NotFoundException('no screenshot');
        return { bytes: Buffer.from(row.screenshot), type: row.screenshotType };
    }

    /**
     * Library templates with DSL that share words with the brief; Gemini gets
     * them as structure references. Cheap keyword overlap, no vectors.
     */
    async examplesFor(text: string, limit = 2): Promise<(TemplateSummary & { dsl: string })[]> {
        const words = [...new Set(text.toLowerCase().match(/[a-z]{4,}/g) ?? [])]
            .filter((w) => !STOP_WORDS.has(w))
            .slice(0, 12);
        const rows = await this.prisma.template.findMany({
            where: { dsl: { not: null } },
            orderBy: { updatedAt: 'desc' },
            take: 60,
            select: { ...SUMMARY_SELECT },
        });
        const scored = rows
            .map((r) => {
                const haystack = `${r.name} ${r.prompt ?? ''} ${r.dsl ?? ''}`.toLowerCase();
                const score = words.reduce((sum, w) => sum + (haystack.includes(w) ? 1 : 0), 0);
                return { row: r, score };
            })
            .filter((x) => x.score > 0)
            .sort((a, b) => b.score - a.score || b.row.updatedAt.getTime() - a.row.updatedAt.getTime())
            .slice(0, limit);
        return scored.map(({ row }) => ({ ...this.summary(row), dsl: row.dsl as string }));
    }

    /* ---------- writes ---------- */

    async create(input: {
        name?: string;
        root: unknown;
        prompt?: string | null;
        dsl?: string | null;
        screenshot?: string | null;
        kind?: TemplateKind;
    }): Promise<TemplateDetail> {
        const root = normalizeNode(input.root as CanvasNode) as CanvasNode;
        const shot = input.screenshot ? decodeDataUrl(input.screenshot) : null;
        const id = newId();
        await this.prisma.template.create({
            data: {
                id,
                name: input.name || String(root.properties.title || 'Untitled'),
                kind: input.kind ?? (input.prompt ? 'ai' : 'user'),
                prompt: input.prompt ?? null,
                dsl: input.dsl ?? null,
                root: root as unknown as Prisma.InputJsonValue,
                screenshot: shot ? new Uint8Array(shot.bytes) : null,
                screenshotType: shot?.type ?? null,
            },
        });
        return this.get(id);
    }

    async update(
        id: string,
        input: { name?: string; root?: unknown; screenshot?: string | null },
    ): Promise<TemplateDetail> {
        const existing = await this.prisma.template.findUnique({ where: { id }, select: { id: true } });
        if (!existing) throw new NotFoundException('not found');
        const shot = input.screenshot ? decodeDataUrl(input.screenshot) : null;
        await this.prisma.template.update({
            where: { id },
            data: {
                name: input.name,
                root: input.root
                    ? (normalizeNode(input.root as CanvasNode) as unknown as Prisma.InputJsonValue)
                    : undefined,
                ...(input.screenshot === undefined
                    ? {}
                    : { screenshot: shot ? new Uint8Array(shot.bytes) : null, screenshotType: shot?.type ?? null }),
            },
        });
        return this.get(id);
    }

    async duplicate(id: string): Promise<TemplateDetail> {
        const source = await this.prisma.template.findUnique({ where: { id } });
        if (!source) throw new NotFoundException('not found');
        return this.create({
            name: `${source.name} (copy)`,
            root: source.root,
            prompt: source.prompt,
            dsl: source.dsl,
            kind: 'user',
        });
    }

    async remove(id: string): Promise<boolean> {
        const result = await this.prisma.template.deleteMany({ where: { id } });
        return result.count > 0;
    }

    /* ---------- seeding ---------- */

    /** Fills an empty library with the web starters plus three large rules-engine templates. */
    async seed(): Promise<number> {
        if ((await this.prisma.template.count()) > 0) return 0;
        let added = 0;
        for (const starter of starters.filter((t) => t.id !== 'blank')) {
            await this.create({ name: starter.name, root: starter.build(), kind: 'starter' });
            added += 1;
        }
        for (const [index, large] of LARGE_STARTERS.entries()) {
            const dsl = generateDsl(large.prompt, {
                type: large.type as never,
                tone: large.tone as never,
                size: 'large',
                seed: 100 + index,
            });
            await this.create({
                name: large.name,
                root: normalizeNode(dslToTree(parseDsl(dsl))),
                prompt: large.prompt,
                dsl,
                kind: 'starter',
            });
            added += 1;
        }
        return added;
    }

    /* ---------- mapping ---------- */

    private summary(r: {
        id: string;
        name: string;
        kind: string;
        prompt: string | null;
        dsl: string | null;
        screenshotType: string | null;
        createdAt: Date;
        updatedAt: Date;
    }): TemplateSummary {
        return {
            id: r.id,
            name: r.name,
            kind: r.kind as TemplateKind,
            prompt: r.prompt,
            hasDsl: r.dsl !== null,
            screenshot: r.screenshotType ? `/api/templates/${r.id}/screenshot` : null,
            createdAt: r.createdAt.toISOString(),
            updatedAt: r.updatedAt.toISOString(),
        };
    }

    /** Keyword search: every word of the query (lightly stemmed) must appear in name, prompt or DSL. */
    private async searchText(q: string, kind: TemplateKind | undefined, limit: number): Promise<TemplateSummary[]> {
        const stems = [...new Set((q.toLowerCase().match(/[a-z0-9]{2,}/g) ?? []).map(stem))].slice(0, 8);
        if (stems.length === 0) return [];
        const rows = await this.prisma.template.findMany({
            where: {
                ...(kind ? { kind } : {}),
                AND: stems.map((word) => ({
                    OR: [
                        { name: { contains: word, mode: 'insensitive' as const } },
                        { prompt: { contains: word, mode: 'insensitive' as const } },
                        { dsl: { contains: word, mode: 'insensitive' as const } },
                    ],
                })),
            },
            orderBy: { updatedAt: 'desc' },
            take: limit,
            select: SUMMARY_SELECT,
        });
        return rows.map((r) => this.summary(r));
    }
}

/** "newsletters" → "newsletter", "sales" → "sale", "stories" → "stor" (still a substring match). */
const stem = (word: string): string =>
    word
        .replace(/ies$/, 'i')
        .replace(/(ses|xes|ches|shes)$/, (m) => m.slice(0, -2))
        .replace(/s$/, '');
