import { Inject, Injectable, Logger, NotFoundException, type OnApplicationBootstrap } from '@nestjs/common';

import type { CanvasNode, EmailNode } from '@email-builder/shared/types';
import { normalizeNode, templates as starters } from '@email-builder/shared/utils';

import { dslToTree, parseDsl } from '../ai/engine/dsl';
import { generateDsl } from '../ai/engine/generator';
import { EmbeddingsService } from '../ai/embeddings.service';
import { decodeDataUrl, newId } from '../common/ids';
import { Prisma } from '../generated/prisma/client';
import { PrismaService } from '../prisma/prisma.service';

export type TemplateKind = 'starter' | 'user' | 'ai';

export interface TemplateSummary {
    id: string;
    name: string;
    kind: TemplateKind;
    prompt: string | null;
    hasDsl: boolean;
    screenshot: string | null;
    createdAt: string;
    updatedAt: string;
    /** Cosine similarity (0..1) when the list came from a vector search. */
    score?: number;
}

export interface TemplateDetail extends TemplateSummary {
    root: CanvasNode;
    dsl: string | null;
}

interface RawRow {
    id: string;
    name: string;
    kind: string;
    prompt: string | null;
    dsl?: string | null;
    has_dsl?: boolean;
    has_shot: boolean;
    created_at: Date;
    updated_at: Date;
    score?: number;
}

const SUMMARY_SELECT = {
    id: true,
    name: true,
    kind: true,
    prompt: true,
    dsl: true,
    screenshotType: true,
    createdAt: true,
    updatedAt: true,
} as const;

/** Large starters generated by the rules engine, so they carry DSL for Gemini examples. */
const LARGE_STARTERS: { name: string; prompt: string; type: string; tone: string }[] = [
    {
        name: 'Large product launch',
        prompt: 'Product launch announcement for Lumen Labs, a SaaS startup, introducing our new Insights dashboard.',
        type: 'announcement',
        tone: 'professional',
    },
    {
        name: 'Large monthly newsletter',
        prompt: 'Monthly newsletter for Bluebird Coffee, a friendly neighbourhood cafe.',
        type: 'newsletter',
        tone: 'friendly',
    },
    {
        name: 'Large seasonal sale',
        prompt: 'End of season sale for Northwind, an online clothing store. 30% off everything.',
        type: 'promo',
        tone: 'urgent',
    },
];

/** Text that represents a template for embeddings and keyword search. */
export const templateText = (name: string, prompt: string | null, dsl: string | null, root: EmailNode): string => {
    const parts: string[] = [name];
    if (prompt) parts.push(prompt);
    if (dsl) parts.push(dsl);
    else {
        const walk = (node: EmailNode): void => {
            Object.entries(node.properties as Record<string, unknown>).forEach(([key, value]) => {
                if (['id', 'type', 'fontFamily', 'align', 'href', 'src', 'url', 'image'].includes(key)) return;
                const push = (v: unknown): void => {
                    if (typeof v === 'string' && v.length > 2 && !/^(#|https?:|data:|rgb)/i.test(v)) {
                        parts.push(v.replace(/<[^>]+>/g, ' '));
                    } else if (Array.isArray(v)) v.forEach(push);
                    else if (v && typeof v === 'object') Object.values(v as Record<string, unknown>).forEach(push);
                };
                push(value);
            });
            node.children.forEach(walk);
        };
        walk(root);
    }
    return parts.join('\n').replace(/\s+/g, ' ').slice(0, 6000);
};

@Injectable()
export class TemplatesService implements OnApplicationBootstrap {
    private readonly logger = new Logger(TemplatesService.name);

    constructor(
        @Inject(PrismaService) private readonly prisma: PrismaService,
        @Inject(EmbeddingsService) private readonly embeddings: EmbeddingsService,
    ) {}

    async onApplicationBootstrap(): Promise<void> {
        try {
            const added = await this.seed();
            if (added > 0) this.logger.log(`seeded ${added} starter templates`);
            await this.reindex();
        } catch (error) {
            this.logger.error(`startup failed: ${(error as Error).message}`);
        }
    }

    /* ---------- reads ---------- */

    async list(query: { q?: string; kind?: TemplateKind; limit?: number }): Promise<TemplateSummary[]> {
        const limit = query.limit ?? 100;
        if (query.q) {
            const embedding = await this.embeddings.embed(query.q, 'RETRIEVAL_QUERY');
            if (embedding) return this.similarByVector(embedding, limit, { kind: query.kind });
            return this.searchText(query.q, query.kind, limit);
        }
        const rows = await this.prisma.template.findMany({
            where: query.kind ? { kind: query.kind } : undefined,
            orderBy: { updatedAt: 'desc' },
            take: limit,
            select: SUMMARY_SELECT,
        });
        return rows.map((r) => this.summary(r));
    }

    async get(id: string): Promise<TemplateDetail> {
        const row = await this.prisma.template.findUnique({ where: { id }, select: { ...SUMMARY_SELECT, root: true } });
        if (!row) throw new NotFoundException('not found');
        return { ...this.summary(row), root: row.root as unknown as CanvasNode, dsl: row.dsl };
    }

    async screenshot(id: string): Promise<{ bytes: Buffer; type: string }> {
        const row = await this.prisma.template.findUnique({
            where: { id },
            select: { screenshot: true, screenshotType: true },
        });
        if (!row?.screenshot || !row.screenshotType) throw new NotFoundException('no screenshot');
        return { bytes: Buffer.from(row.screenshot), type: row.screenshotType };
    }

    /** Nearest neighbours of a stored template (falls back to same-kind recents without embeddings). */
    async similar(id: string, limit = 6): Promise<TemplateSummary[]> {
        const rows = await this.prisma.$queryRaw<RawRow[]>`
            SELECT t.id, t.name, t.kind, t.prompt, t.dsl IS NOT NULL AS has_dsl, t.screenshot_type IS NOT NULL AS has_shot,
                   t.created_at, t.updated_at, 1 - (t.embedding <=> s.embedding) AS score
            FROM templates t, (SELECT embedding FROM templates WHERE id = ${id}) s
            WHERE t.id <> ${id} AND t.embedding IS NOT NULL AND s.embedding IS NOT NULL
            ORDER BY t.embedding <=> s.embedding
            LIMIT ${limit}`;
        if (rows.length > 0) return rows.map((r) => this.fromRaw(r));
        const source = await this.prisma.template.findUnique({ where: { id }, select: { kind: true } });
        if (!source) throw new NotFoundException('not found');
        const sameKind = await this.prisma.template.findMany({
            where: { id: { not: id }, kind: source.kind },
            orderBy: { updatedAt: 'desc' },
            take: limit,
            select: SUMMARY_SELECT,
        });
        const recents =
            sameKind.length > 0
                ? sameKind
                : await this.prisma.template.findMany({
                      where: { id: { not: id } },
                      orderBy: { updatedAt: 'desc' },
                      take: limit,
                      select: SUMMARY_SELECT,
                  });
        return recents.map((r) => this.summary(r));
    }

    /** pgvector cosine search; `withDsl` restricts to templates Gemini can use as examples. */
    async similarByVector(
        embedding: number[],
        limit: number,
        filter: { kind?: TemplateKind; withDsl?: boolean } = {},
    ): Promise<(TemplateSummary & { dsl: string | null })[]> {
        const vector = JSON.stringify(embedding);
        const rows = await this.prisma.$queryRaw<(RawRow & { dsl: string | null })[]>`
            SELECT id, name, kind, prompt, dsl, dsl IS NOT NULL AS has_dsl, screenshot_type IS NOT NULL AS has_shot,
                   created_at, updated_at, 1 - (embedding <=> ${vector}::vector) AS score
            FROM templates
            WHERE embedding IS NOT NULL
              AND (${filter.kind ?? null}::text IS NULL OR kind = ${filter.kind ?? null})
              AND (${filter.withDsl ?? false}::boolean = false OR dsl IS NOT NULL)
            ORDER BY embedding <=> ${vector}::vector
            LIMIT ${limit}`;
        return rows.map((r) => ({ ...this.fromRaw(r), dsl: r.dsl }));
    }

    /* ---------- writes ---------- */

    async create(input: {
        name?: string;
        root: unknown;
        prompt?: string | null;
        dsl?: string | null;
        screenshot?: string | null;
        kind?: TemplateKind;
    }): Promise<TemplateDetail> {
        const root = normalizeNode(input.root as CanvasNode) as CanvasNode;
        const shot = input.screenshot ? decodeDataUrl(input.screenshot) : null;
        const id = newId();
        await this.prisma.template.create({
            data: {
                id,
                name: input.name || String(root.properties.title || 'Untitled'),
                kind: input.kind ?? (input.prompt ? 'ai' : 'user'),
                prompt: input.prompt ?? null,
                dsl: input.dsl ?? null,
                root: root as unknown as Prisma.InputJsonValue,
                screenshot: shot ? new Uint8Array(shot.bytes) : null,
                screenshotType: shot?.type ?? null,
            },
        });
        await this.embedTemplate(id);
        return this.get(id);
    }

    async update(
        id: string,
        input: { name?: string; root?: unknown; screenshot?: string | null },
    ): Promise<TemplateDetail> {
        const existing = await this.prisma.template.findUnique({ where: { id }, select: { id: true } });
        if (!existing) throw new NotFoundException('not found');
        const shot = input.screenshot ? decodeDataUrl(input.screenshot) : null;
        await this.prisma.template.update({
            where: { id },
            data: {
                name: input.name,
                root: input.root
                    ? (normalizeNode(input.root as CanvasNode) as unknown as Prisma.InputJsonValue)
                    : undefined,
                ...(input.screenshot === undefined
                    ? {}
                    : { screenshot: shot ? new Uint8Array(shot.bytes) : null, screenshotType: shot?.type ?? null }),
            },
        });
        if (input.name || input.root) await this.embedTemplate(id);
        return this.get(id);
    }

    async duplicate(id: string): Promise<TemplateDetail> {
        const source = await this.prisma.template.findUnique({ where: { id } });
        if (!source) throw new NotFoundException('not found');
        return this.create({
            name: `${source.name} (copy)`,
            root: source.root,
            prompt: source.prompt,
            dsl: source.dsl,
            kind: 'user',
        });
    }

    async remove(id: string): Promise<boolean> {
        const result = await this.prisma.template.deleteMany({ where: { id } });
        return result.count > 0;
    }

    /* ---------- embeddings ---------- */

    /** (Re)computes the pgvector embedding of one template; no-op without an embeddings provider. */
    async embedTemplate(id: string): Promise<boolean> {
        if (!this.embeddings.enabled) return false;
        const row = await this.prisma.template.findUnique({ where: { id }, select: { ...SUMMARY_SELECT, root: true } });
        if (!row) return false;
        const text = templateText(row.name, row.prompt, row.dsl, row.root as unknown as EmailNode);
        const embedding = await this.embeddings.embed(text, 'RETRIEVAL_DOCUMENT');
        if (!embedding) return false;
        await this.prisma
            .$executeRaw`UPDATE templates SET embedding = ${JSON.stringify(embedding)}::vector WHERE id = ${id}`;
        return true;
    }

    /** Embeds templates that have no vector yet (rows written while the provider was off). */
    async reindex(max = 50): Promise<number> {
        if (!this.embeddings.enabled) return 0;
        const missing = await this.prisma.$queryRaw<{ id: string }[]>`
            SELECT id FROM templates WHERE embedding IS NULL ORDER BY updated_at DESC LIMIT ${max}`;
        let done = 0;
        for (const { id } of missing) {
            if (await this.embedTemplate(id)) done += 1;
        }
        if (done > 0) this.logger.log(`embedded ${done} templates for pgvector search`);
        return done;
    }

    /* ---------- seeding ---------- */

    /** Fills an empty library with the web starters plus three large rules-engine templates. */
    async seed(): Promise<number> {
        if ((await this.prisma.template.count()) > 0) return 0;
        let added = 0;
        for (const starter of starters.filter((t) => t.id !== 'blank')) {
            await this.create({ name: starter.name, root: starter.build(), kind: 'starter' });
            added += 1;
        }
        for (const [index, large] of LARGE_STARTERS.entries()) {
            const dsl = generateDsl(large.prompt, {
                type: large.type as never,
                tone: large.tone as never,
                size: 'large',
                seed: 100 + index,
            });
            await this.create({
                name: large.name,
                root: normalizeNode(dslToTree(parseDsl(dsl))),
                prompt: large.prompt,
                dsl,
                kind: 'starter',
            });
            added += 1;
        }
        return added;
    }

    /* ---------- mapping ---------- */

    private summary(r: {
        id: string;
        name: string;
        kind: string;
        prompt: string | null;
        dsl: string | null;
        screenshotType: string | null;
        createdAt: Date;
        updatedAt: Date;
    }): TemplateSummary {
        return {
            id: r.id,
            name: r.name,
            kind: r.kind as TemplateKind,
            prompt: r.prompt,
            hasDsl: r.dsl !== null,
            screenshot: r.screenshotType ? `/api/templates/${r.id}/screenshot` : null,
            createdAt: r.createdAt.toISOString(),
            updatedAt: r.updatedAt.toISOString(),
        };
    }

    private fromRaw(r: RawRow): TemplateSummary {
        return {
            id: r.id,
            name: r.name,
            kind: r.kind as TemplateKind,
            prompt: r.prompt,
            hasDsl: r.has_dsl ?? r.dsl != null,
            screenshot: r.has_shot ? `/api/templates/${r.id}/screenshot` : null,
            createdAt: new Date(r.created_at).toISOString(),
            updatedAt: new Date(r.updated_at).toISOString(),
            score: r.score === undefined ? undefined : Number(r.score),
        };
    }

    private async searchText(q: string, kind: TemplateKind | undefined, limit: number): Promise<TemplateSummary[]> {
        const rows = await this.prisma.template.findMany({
            where: {
                ...(kind ? { kind } : {}),
                OR: [
                    { name: { contains: q, mode: 'insensitive' } },
                    { prompt: { contains: q, mode: 'insensitive' } },
                    { dsl: { contains: q, mode: 'insensitive' } },
                ],
            },
            orderBy: { updatedAt: 'desc' },
            take: limit,
            select: SUMMARY_SELECT,
        });
        return rows.map((r) => this.summary(r));
    }
}
